# Generated by Django 5.1.1 on 2024-10-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_invoice_date_invoice_is_successful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='is_successful',
            new_name='paid',
        ),
    ]
