# Generated by Django 5.1.1 on 2024-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_pricingplans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplans',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
