# Generated by Django 5.1.1 on 2024-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_alter_pricingplans_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplans',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
