# Generated by Django 5.1.1 on 2024-10-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_alter_pricingplans_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
