# Generated by Django 5.1.1 on 2024-10-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_alter_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('payment_failed', 'Payment Failed')], default='inactive', max_length=20),
        ),
    ]
