# Generated by Django 5.1.1 on 2024-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
