# Generated by Django 5.1.1 on 2024-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_booking_type_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='battery_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
