# Generated by Django 5.1.1 on 2024-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_booking_battery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_image',
            field=models.URLField(),
        ),
    ]
