# Generated by Django 5.1.1 on 2024-10-07 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_booking_paid_alter_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
