# Generated by Django 5.1.1 on 2024-10-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_booking_invoice_id_booking_price_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_date_and_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
