# Generated by Django 5.1.1 on 2024-09-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, help_text="User's profile image", null=True, upload_to='images/profile-photos/'),
        ),
    ]
