# Generated by Django 5.1.1 on 2024-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_user_vehicle_type_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, help_text="User's profile image", null=True),
        ),
    ]
