# Generated by Django 5.1.1 on 2024-10-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_type',
            field=models.CharField(default='Visitor', max_length=50),
        ),
    ]
